---
- type: replace
  path: /instance_groups/name=credhub/jobs/name=credhub/provides?
  value: { credhub: nil }
- type: replace
  path: /instance_groups/name=credhub/jobs/-
  value:
    name: route_registrar
    release: routing
    properties:
      route_registrar:
        routes:
        - name: credhub
          tls_port: 8844
          server_cert_domain_san: credhub.service.cf.internal
          registration_interval: 10s
          tags:
            component: credhub
          uris:
          - credhub.((system_domain))
